server:
  port: 8088

eureka:
  eureka:
    server:
      enableSelfPreservation: false
  instance:
    hostname: eureka-server-for-money-turn.herokuapp.com

  client:
    fetch-registry: false
    register-with-eureka: false
  serviceUrl:
    defaultZone: https://eureka-server-for-money-turn.herokuapp.com/eureka

